name: Terraform Apply or Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP A: Pull down the state history from your previous runs
      - name: Download Existing State History
        uses: actions/download-artifact@v4
        with:
          name: tf-state-storage
          path: .
        continue-on-error: true # Safe if this is the first run

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      # Will run if you select 'apply'
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      # Will run if you select 'destroy'
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve

      # STEP B: Save the new/updated state history back to GitHub
      - name: Save Updated State File
        if: always() # Runs even if creation or destruction fails
        uses: actions/upload-artifact@v4
        with:
          name: tf-state-storage
          path: terraform.tfstate
          if-no-files-found: ignore
